version: '3'
services:
  redis:
    image:
    ports:
      - "6379"
    networks:
      - e5Code
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
