Name: project.rpc
ListenOn: 0.0.0.0:8002
Etcd:
  Hosts:
  - frp.byt0723.xyz:2379
  Key: project.rpc
Mysql:
  DataSource: root:wangtao@tcp(frp.byt0723.xyz:3306)/test?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: frp.byt0723.xyz:6379
    Pass: wangtao
    Type: node
