Name: project.rpc
ListenOn: 0.0.0.0:8002
Etcd:
  Hosts:
    - etcd:2379
  Key: project.rpc
GitRegistryUrl:
  Http: 42.192.5.238
  SSH: git.byt0723.xyz
RepositoryConf:
  Repositories: /tmp/e5Code/repositories
  Tars: /tmp/e5Code/tars
  BuildLogs: /tmp/e5Code/build_logs
Mysql:
  DataSource: root:wangtao@tcp(db:3306)/e5Code?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: redis:6379
    Type: node
UserRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: user.rpc
  NonBlock: true
