// Code generated by goctl. DO NOT EDIT!
// Source: ci.proto

package server

import (
	"context"

	"e5Code-Service/service/ci/rpc/internal/logic"
	"e5Code-Service/service/ci/rpc/internal/svc"
	"e5Code-Service/service/ci/rpc/pb"
)

type CiServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCiServer
}

func NewCiServer(svcCtx *svc.ServiceContext) *CiServer {
	return &CiServer{
		svcCtx: svcCtx,
	}
}

func (s *CiServer) BuildImage(ctx context.Context, in *pb.BuildReq) (*pb.BuildRsp, error) {
	l := logic.NewBuildImageLogic(ctx, s.svcCtx)
	return l.BuildImage(in)
}
