// Code generated by goctl. DO NOT EDIT!
// Source: deploy.proto

package server

import (
	"context"

	"e5Code-Service/service/project/rpc/internal/logic"
	"e5Code-Service/service/project/rpc/internal/svc"
	"e5Code-Service/service/project/rpc/project"
)

type DepolyServer struct {
	svcCtx *svc.ServiceContext
}

func NewDepolyServer(svcCtx *svc.ServiceContext) *DepolyServer {
	return &DepolyServer{
		svcCtx: svcCtx,
	}
}

func (s *DepolyServer) GetDepoly(ctx context.Context, in *project.GetDeployReq) (*project.GetDeployRsp, error) {
	l := logic.NewGetDepolyLogic(ctx, s.svcCtx)
	return l.GetDepoly(in)
}

func (s *DepolyServer) AddDeploy(ctx context.Context, in *project.AddDeployReq) (*project.AddDeployRsp, error) {
	l := logic.NewAddDeployLogic(ctx, s.svcCtx)
	return l.AddDeploy(in)
}

func (s *DepolyServer) UpdateDeploy(ctx context.Context, in *project.UpdateDeployReq) (*project.UpdateDeployRsp, error) {
	l := logic.NewUpdateDeployLogic(ctx, s.svcCtx)
	return l.UpdateDeploy(in)
}

func (s *DepolyServer) DeleteDeploy(ctx context.Context, in *project.DeleteDeployReq) (*project.DeleteDeployRsp, error) {
	l := logic.NewDeleteDeployLogic(ctx, s.svcCtx)
	return l.DeleteDeploy(in)
}
