// Code generated by goctl. DO NOT EDIT!
// Source: project.proto

package server

import (
	"context"

	"e5Code-Service/service/project/rpc/internal/logic"
	"e5Code-Service/service/project/rpc/internal/svc"
	"e5Code-Service/service/project/rpc/project"
)

type ProjectServer struct {
	svcCtx *svc.ServiceContext
}

func NewProjectServer(svcCtx *svc.ServiceContext) *ProjectServer {
	return &ProjectServer{
		svcCtx: svcCtx,
	}
}

func (s *ProjectServer) GetProject(ctx context.Context, in *project.GetProjectReq) (*project.GetProjectRsp, error) {
	l := logic.NewGetProjectLogic(ctx, s.svcCtx)
	return l.GetProject(in)
}

func (s *ProjectServer) AddProject(ctx context.Context, in *project.AddProjectReq) (*project.AddProjectRsp, error) {
	l := logic.NewAddProjectLogic(ctx, s.svcCtx)
	return l.AddProject(in)
}

func (s *ProjectServer) UpdateProject(ctx context.Context, in *project.UpdateProjectReq) (*project.UpdateProjectRsp, error) {
	l := logic.NewUpdateProjectLogic(ctx, s.svcCtx)
	return l.UpdateProject(in)
}

func (s *ProjectServer) DeleteProject(ctx context.Context, in *project.DeleteProjectReq) (*project.DeleteProjectRsp, error) {
	l := logic.NewDeleteProjectLogic(ctx, s.svcCtx)
	return l.DeleteProject(in)
}
