// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"e5Code-Service/service/project/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/project/getProject/:id",
				Handler: getProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/addProject",
				Handler: addProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/updateProject",
				Handler: updateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/project/deleteProject",
				Handler: deleteProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/project/getDeploy/:id",
				Handler: getDeployHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/addDeploy",
				Handler: addDeployHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/updateDeploy",
				Handler: updateDeployHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/project/deleteDeploy",
				Handler: deleteDeployHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/deploy",
				Handler: deployHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
