// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"e5Code-Service/service/ci/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LoadValue},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/ci/getBuildPlan",
					Handler: getBuildPlanHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ci/addBuildPlan",
					Handler: addBuildPlanHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ci/updateBuildPlan",
					Handler: updateBuildPlanHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ci/deleteBuildPlan",
					Handler: deleteBuildPlanHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ci/listBuildPlan",
					Handler: listBuildPlanHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ci/getImage",
					Handler: getImageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ci/deleteImage",
					Handler: deleteImageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ci/listImage",
					Handler: listImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
