// Code generated by goctl. DO NOT EDIT.
package types

type Project struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Desc    string `json:"desc"`
	Url     string `json:"url"`
	OwnerId string `json:"owner_id"`
}

type GetProjectReq struct {
	ID string `json:"id"`
}

type GetProjectReply struct {
	Result Project `json:"result"`
}

type AddProjectReq struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Url  string `json:"url"`
}

type AddProjectReply struct {
	Result Project `json:"result"`
}

type UpdateProjectReq struct {
	Payload Project `json:"payload"`
}

type UpdateProjectReply struct {
	Result bool `json:"result"`
}

type DeleteProjectReq struct {
	ID string `json:"id"`
}

type DeleteProjectReply struct {
	Result bool `json:"result"`
}
